"""add_user_school_to_questions

Revision ID: 9c6668186757
Revises: 322e870b69de
Create Date: 2026-02-22 22:22:22.456185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c6668186757'
down_revision = '322e870b69de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Clean up old tables first
    op.drop_table('assignmentprogress')

    # 2. Add the user_school column if it doesn't exist, or make it nullable for a second
    # If op.add_column isn't here, it's because it was added in a previous revision.
    # We will ensure all rows have a value before setting nullable=False.
    
    # 3. DATA MIGRATION: Give old questions a default school so they aren't NULL
    op.execute("UPDATE question SET user_school = 'UCSB' WHERE user_school IS NULL")
    op.execute("UPDATE question SET course = 'General' WHERE course IS NULL")
    op.execute("UPDATE question SET correct_answer = 'Pending' WHERE correct_answer IS NULL")
    op.execute("UPDATE question SET user_id = 'Unknown' WHERE user_id IS NULL")

    # 4. Now that data exists, apply the strict NOT NULL constraints
    op.alter_column('question', 'user_school',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question', 'course',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question', 'correct_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # Existing generated logic for other tables
    op.alter_column('assignment', 'assignment_questions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('course', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('question', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('question', 'correct_answer',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('question', 'course',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('question', 'user_school',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('course', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assignment', 'assignment_questions',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.create_table('assignmentprogress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answers', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('current_question_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('submitted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name='assignmentprogress_assignment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], name='assignmentprogress_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assignmentprogress_pkey'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='assignmentprogress_assignment_id_student_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
